-- owner: catalog
INSERT INTO resource_provider_catalog(id, label, provider_type, endpoint, sort_order) VALUES
('azure-openai', 'Azure OpenAI', 'openai-compatible', '', 15),
('google-gemini', 'Google Gemini', 'openai-compatible', 'https://generativelanguage.googleapis.com/v1beta/openai', 25),
('openrouter', 'OpenRouter', 'openai-compatible', 'https://openrouter.ai/api', 35),
('qwen', 'Alibaba Cloud DashScope / Qwen', 'openai-compatible', 'https://dashscope.aliyuncs.com/compatible-mode', 45),
('zhipu', 'Zhipu AI', 'openai-compatible', 'https://open.bigmodel.cn/api/paas', 55),
('baidu-qianfan', 'Baidu Qianfan', 'openai-compatible', 'https://qianfan.baidubce.com/v2', 65),
('volcengine-ark', 'Volcengine Ark / Doubao', 'openai-compatible', 'https://ark.cn-beijing.volces.com/api', 75),
('tencent-hunyuan', 'Tencent Hunyuan', 'openai-compatible', 'https://api.hunyuan.cloud.tencent.com', 85),
('minimax', 'MiniMax', 'openai-compatible', 'https://api.minimax.chat/v1', 95),
('01ai', '01.AI', 'openai-compatible', 'https://api.lingyiwanwu.com/v1', 105),
('mistral', 'Mistral AI', 'openai-compatible', 'https://api.mistral.ai/v1', 115),
('cohere', 'Cohere', 'openai-compatible', 'https://api.cohere.com/compatibility/v1', 125),
('xai', 'xAI', 'openai-compatible', 'https://api.x.ai/v1', 135),
('groq', 'Groq', 'openai-compatible', 'https://api.groq.com/openai', 145),
('together', 'Together AI', 'openai-compatible', 'https://api.together.xyz/v1', 155),
('fireworks', 'Fireworks AI', 'openai-compatible', 'https://api.fireworks.ai/inference/v1', 165),
('perplexity', 'Perplexity', 'openai-compatible', 'https://api.perplexity.ai', 175),
('lmstudio', 'LM Studio', 'openai-compatible', 'http://127.0.0.1:1234/v1', 185)
ON CONFLICT(id) DO NOTHING;

INSERT INTO resource_model_catalog(id, provider_id, model, capabilities, context_window, sort_order) VALUES
('google-gemini-2-5-pro', 'google-gemini', 'gemini-2.5-pro', '["chat","vision","reasoning"]', 1048576, 10),
('google-gemini-2-5-flash', 'google-gemini', 'gemini-2.5-flash', '["chat","vision"]', 1048576, 20),
('openrouter-auto', 'openrouter', 'openrouter/auto', '["chat"]', NULL, 10),
('qwen-plus', 'qwen', 'qwen-plus', '["chat"]', 131072, 10),
('qwen-max', 'qwen', 'qwen-max', '["chat"]', 32768, 20),
('qwen-turbo', 'qwen', 'qwen-turbo', '["chat"]', 1000000, 30),
('zhipu-glm-4-plus', 'zhipu', 'glm-4-plus', '["chat"]', 128000, 10),
('zhipu-glm-4-flash', 'zhipu', 'glm-4-flash', '["chat"]', 128000, 20),
('baidu-ernie-4-turbo', 'baidu-qianfan', 'ernie-4.0-turbo-8k', '["chat"]', 8192, 10),
('volcengine-doubao-pro', 'volcengine-ark', 'doubao-pro-32k', '["chat"]', 32768, 10),
('volcengine-doubao-lite', 'volcengine-ark', 'doubao-lite-32k', '["chat"]', 32768, 20),
('tencent-hunyuan-turbo', 'tencent-hunyuan', 'hunyuan-turbo', '["chat"]', 32768, 10),
('minimax-abab6-5s', 'minimax', 'abab6.5s-chat', '["chat"]', 245760, 10),
('01ai-yi-large', '01ai', 'yi-large', '["chat"]', 32768, 10),
('mistral-large-latest', 'mistral', 'mistral-large-latest', '["chat"]', 128000, 10),
('mistral-small-latest', 'mistral', 'mistral-small-latest', '["chat"]', 32000, 20),
('cohere-command-r-plus', 'cohere', 'command-r-plus', '["chat"]', 128000, 10),
('xai-grok-4', 'xai', 'grok-4', '["chat","reasoning"]', 256000, 10),
('xai-grok-3', 'xai', 'grok-3', '["chat"]', 131072, 20),
('groq-llama-3-1-70b', 'groq', 'llama-3.1-70b-versatile', '["chat"]', 131072, 10),
('groq-mixtral', 'groq', 'mixtral-8x7b-32768', '["chat"]', 32768, 20),
('together-llama-3-1-405b', 'together', 'meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo', '["chat"]', 131072, 10),
('fireworks-llama-v3p1-405b', 'fireworks', 'accounts/fireworks/models/llama-v3p1-405b-instruct', '["chat"]', 131072, 10),
('perplexity-sonar-pro', 'perplexity', 'sonar-pro', '["chat","search"]', 200000, 10),
('lmstudio-local-model', 'lmstudio', 'local-model', '["chat"]', NULL, 10)
ON CONFLICT(id) DO NOTHING;
